[package]
name = "scoutable"
version = "0.5.0"
description = "Scoutable desktop"
authors = ["Scoutable"]
edition = "2021"

[lib]
name = "scoutable_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-opener = "2"
tauri-plugin-http = "2"
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
tauri-plugin-deep-link = "2"
tauri-plugin-sentry = "0.6"
sentry = "0.49"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
percent-encoding = "2"
http-range = "0.1"
ab_glyph = "0.2"
image = "0.25"
imageproc = "0.25"
